sudo: false

language: go
go:
  - 1.5.1

before_install:
  # This is needed so the package path uses elastic/winlogbeat as its path.
  - mkdir -p $HOME/gopath/src/github.com/elastic/winlogbeat
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/elastic/winlogbeat/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/elastic/winlogbeat
  - cd $HOME/gopath/src/github.com/elastic/winlogbeat

install:
  - make deps

script:
  - make check
  - make winlogbeat
  - make testsuite
  - make crosscompile

after_success:
  # Copy profile.cov to coverage.txt because codecov.io requires this file
  - test -f build/coverage/full.cov && bash <(curl -s https://codecov.io/bash) -f build/coverage/full.cov
