language: go

go:
  - 1.5.3

addons:
  apt:
    packages:
      - python-virtualenv

before_script:
  - wget https://github.com/Masterminds/glide/releases/download/0.8.3/glide-0.8.3-linux-386.tar.gz -O /tmp/glide.tar.gz
  - tar -xvf /tmp/glide.tar.gz
  - export PATH=$PATH:$PWD/linux-386/

script:
  - make test
